### PR TITLE
Fixing things atm

### PR DESCRIPTION
**Pull request by kuddlefishbwaa**
Still working on it but this should help

### CODE REVIEW

**Review by Stowne1 — APPROVED** [review]
some nice stuff right here.

**Review by brendacastel1 — APPROVED** [review]
Awesome thank you for doing this!

**Review by Stowne1 — DISMISSED** [review]
looking good!

**Review by Stowne1 — APPROVED** [review]
Thank you Thank you!

**Review by Ciscoslahs — DISMISSED** [review]
Looks like this should work

**Pull request merged**
